#docker-compose up -dV --build --remove-orphan --force-recreate
# docker-compose up -dV --remove-orphan --force-recreate
# docker network create vrkansagara-network
services:
    app:
        image: 'vrkansagara:latest'
        container_name: vrkansagara_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - '80:80'
            - '443:442'
            - '8000:8000'
        restart: unless-stopped
        tty: true
        volumes:
            - '.:/var/www/vrkansagara.in:rw'
        networks:
            - vrkansagara-network
networks:
    vrkansagara-network:
