# Use an ARG to define the Node.js version to make it easily updatable
ARG NODE_VERSION=23.3.0

# Base image
FROM node:${NODE_VERSION}-alpine

#Defining the user to avoid permission on shared volumes
USER node