#!/usr/bin/env bash
set -e # This setting is telling the script to exit on a command error.
if [[ "$1" == "-v" ]]; then
  set -x # You refer to a noisy script.(Used to debugging)
fi


# Ref:- https://github.com/tpope/vim-fugitive/commit/63a05a6935ec4a45551bf141089c13d5671202a1

if [ -d doc -a \( -d autoload -o -d ftdetect -o -d plugin \) ]; then
  nohup vim -u NONE -c 'helptags doc' -cq >/dev/null 2>&1 </dev/null &
fi

optfiles=`git ls-files -oc --directory -- .ctags '*/.ctags'`

IFS='
'
for optfile in ${optfiles:-./fake}; do
  (
  unset GIT_DIR GIT_WORK_TREE
  tmpfile=`mktemp ${TMPDIR:-/tmp}/tags.XXXXXXXXXX~`
  cd `dirname $optfile`
  trap 'rm -f $tmpfile' EXIT INT TERM
  git ls-files | ctags -L - -f $tmpfile "$@"
  mv $tmpfile tags
  )
done
