services:
  node:
    build:
      context: ./nodejs
    tty: true
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    container_name: node
    networks:
      - default
networks:
  default:
    driver: bridge